CREATE TABLE IF NOT EXISTS styles (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS artists (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS styles_artists (
	id SERIAL PRIMARY KEY,
	style_id INTEGER NOT NULL REFERENCES styles(id),
	artist_id INTEGER NOT NULL REFERENCES artists(id)
);


CREATE TABLE IF NOT EXISTS albums (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) UNIQUE NOT NULL,
	year INTEGER
);

CREATE TABLE IF NOT EXISTS albums_artists (
	id SERIAL PRIMARY KEY,
	album_id INTEGER NOT NULL REFERENCES albums(id),
	artist_id INTEGER NOT NULL REFERENCES artists(id)
);

CREATE TABLE IF NOT EXISTS tracks (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100),
	duration INTEGER,
	album_id INTEGER NOT NULL REFERENCES albums(id)
);

CREATE TABLE IF NOT EXISTS digests (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) UNIQUE NOT NULL,
    year INTEGER

);

CREATE TABLE IF NOT EXISTS digests_tracks (
	id SERIAL PRIMARY KEY,
	digest_id INTEGER NOT NULL REFERENCES digests(id),
	track_id INTEGER NOT NULL REFERENCES tracks(id)
);
